import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import styles from '../styles/Home.module.scss'
import software from '../public/png-clipart-responsive-web-design-web-development-magento-e-commerce-ecommerce-electronics-gadget-thumbnail-removebg-preview.png';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Revyfy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.textContainer}>
        <p className={styles.businessFasterHeading}>MAKE YOUR BUSINESS <br /><span className={styles.primaryClrText}>BETTER {'&'} FASTER !</span> </p>
        <p className={styles.introTextContainer}>Get a salon management software that is dedicated to growing every aspect of your business. Born on the salon floor, bred to help you thrive.</p>
      </div>
      <div className={styles.softwarePictureContainer}>
        <Image src={software} />
      </div>
    </div>
  )
}
